In [486]:
import numpy as np

In [487]:
ndr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]]) # ndimensional array
ndr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [488]:
ar=np.arange(10) #arange nums without typing whole nums
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [489]:
steps=np.arange(1,10,2) #arange even nums in given value 
steps

array([1, 3, 5, 7, 9])

In [490]:
spc=np.linspace(1,10,5)#it brokes 1 to 10 nums into 5 equally space intervals
spc

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [491]:
ar.size # it shows the size of the array

10

In [492]:
ndr.shape # shape command shows the matrix of the array

(3, 3)

In [493]:
np.zeros(6)# to create a number of zeros in array

array([0., 0., 0., 0., 0., 0.])

In [494]:
np.zeros((4,4)) # it creates the ndarray of the zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [495]:
np.ones((1,2)) # creates the "ones" no of the array

array([[1., 1.]])

In [496]:
rand=np.random.randint(1,100,20) # creates the random no of the given values in array
rand

array([ 6, 59, 96,  8, 92, 81, 72, 43, 82, 72, 36, 93, 44, 85, 10,  8, 63,
       28, 39, 48])

In [497]:
rand.min() # find the min values in array

6

In [498]:
rand.max() #find the max values in the array

96

In [499]:
rand.argmax() # arg shows the location of the maximum & minimum value

2

In [500]:
rand.reshape(2,10) #reshape the random arrays in 2x10 shape

array([[ 6, 59, 96,  8, 92, 81, 72, 43, 82, 72],
       [36, 93, 44, 85, 10,  8, 63, 28, 39, 48]])

In [501]:
ar=np.arange(1,30,2)


In [502]:
ar[5] # shows the value of the 5th index in array list 

11

In [503]:
ar[5:10] # shows the index value of the 5 to 10

array([11, 13, 15, 17, 19])

In [504]:
ar[:5]=10 # changes the values of the given range index
ar

array([10, 10, 10, 10, 10, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [505]:
cpy=ar.copy()
cpy[:4]=8 # copy the array
cpy

array([ 8,  8,  8,  8, 10, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [506]:
ar

array([10, 10, 10, 10, 10, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [507]:
"""TWO DIMENSIONAL ARRAYS"""

'TWO DIMENSIONAL ARRAYS'

In [508]:
ndr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [509]:
ndr[1][0]

4

In [510]:
ndr[0,0] # this method is same as ndr[0][0]

1

In [511]:
ndr[:1,]

array([[1, 2, 3]])

In [512]:
ndr[:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [513]:
ndr[:3,]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [528]:
ndr[1:2] # it extracts the 2nd row

array([[4, 5, 6]])

In [515]:
ndr[0:3,0:1]

array([[1],
       [4],
       [7]])

In [516]:
ndr[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [567]:
ndr[0:,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [564]:
ndr[1 # it selects the 1st column in array
    ,0:] # 1st value selects the row & second value selects the column

array([4, 5, 6])

In [548]:
ndr[0,0:2]

array([1, 2])

In [568]:
ndr[2,0:3]

array([7, 8, 9])